import "server-only";
import { auth } from "@clerk/nextjs/server";
const ID=/^[A-Za-z0-9_-]{1,128}$/;
export class TeacherProxyError extends Error { constructor(readonly status:number,readonly code:string,message:string){super(message)} }
export type TeacherOperation = {kind:"listClasses"}|{kind:"createClass";body:string}|{kind:"createInvite";classId:string;body:string}|{kind:"listRoster";classId:string}|{kind:"listAssignments";classId:string}|{kind:"createAssignment";classId:string;body:string};
const id=(value:string)=>{if(!ID.test(value))throw new TeacherProxyError(400,"invalid_id","identifier is invalid");return value};
/** Parses and canonicalizes teacher mutation JSON before Clerk auth or Core is contacted. */
export function validateTeacherBody(kind:"class"|"invite"|"assignment", raw:string):string { if(raw.length===0||raw.length>8192)throw new TeacherProxyError(400,"invalid_json","request body is invalid");let body:unknown;try{body=JSON.parse(raw)}catch{throw new TeacherProxyError(400,"invalid_json","request body is invalid")};if(!body||typeof body!=="object"||Array.isArray(body))throw new TeacherProxyError(400,"invalid_json","request body is invalid");const x=body as Record<string,unknown>;const exact=(keys:string[])=>Object.keys(x).length===keys.length&&keys.every(k=>Object.hasOwn(x,k));if(kind==="class"){if(!exact(["name"])||typeof x.name!=="string"||!x.name.trim()||Array.from(x.name.trim()).length>120)throw new TeacherProxyError(400,"invalid_input","request is invalid");return JSON.stringify({name:x.name.trim()})}if(kind==="invite"){if(!exact(["ttlSeconds","maxUses"])||!Number.isSafeInteger(x.ttlSeconds)||!Number.isSafeInteger(x.maxUses)||x.ttlSeconds<60||x.ttlSeconds>2592000||x.maxUses<1||x.maxUses>100)throw new TeacherProxyError(400,"invalid_input","request is invalid");return JSON.stringify({ttlSeconds:x.ttlSeconds,maxUses:x.maxUses})}if(!exact(["title","syllabusId","moduleId","questionIds","markingMode"])||typeof x.title!=="string"||!x.title.trim()||Array.from(x.title.trim()).length>160||typeof x.syllabusId!=="string"||typeof x.moduleId!=="string"||!ID.test(x.syllabusId)||!ID.test(x.moduleId)||!Array.isArray(x.questionIds)||x.questionIds.length<1||x.questionIds.length>50||!x.questionIds.every(v=>typeof v==="string"&&ID.test(v))||new Set(x.questionIds).size!==x.questionIds.length||(x.markingMode!=="automated"&&x.markingMode!=="manual_teacher"))throw new TeacherProxyError(400,"invalid_input","request is invalid");return JSON.stringify({title:x.title.trim(),syllabusId:x.syllabusId,moduleId:x.moduleId,questionIds:x.questionIds,markingMode:x.markingMode}) }
function route(op:TeacherOperation){switch(op.kind){case"listClasses":return ["GET","/teacher/classes"] as const;case"createClass":return["POST","/teacher/classes",op.body]as const;case"createInvite":return["POST",`/teacher/classes/${id(op.classId)}/invites`,op.body]as const;case"listRoster":return["GET",`/teacher/classes/${id(op.classId)}/roster`]as const;case"listAssignments":return["GET",`/teacher/classes/${id(op.classId)}/assignments`]as const;case"createAssignment":return["POST",`/teacher/classes/${id(op.classId)}/assignments`,op.body]as const}}
export async function callTeacherCore(op:TeacherOperation):Promise<{status:number;body:unknown}>{const base=process.env.SIDUS_CORE_API_URL;if(!base)throw new TeacherProxyError(503,"service_unavailable","teacher service is not configured");const [method,path,body]=route(op);const {getToken}=await auth();const token=await getToken();if(!token)throw new TeacherProxyError(401,"unauthorized","sign-in is required");try{const response=await fetch(`${base.replace(/\/+$/,"")}${path}`,{method,headers:{Authorization:`Bearer ${token}`,Accept:"application/json",...(body?{"Content-Type":"application/json"}:{})},body,redirect:"error"});if(response.status>=500){await response.text();throw new TeacherProxyError(502,"upstream_error","teacher service unavailable")}const text=await response.text();return{status:response.status,body:text?JSON.parse(text):null}}catch(e){if(e instanceof TeacherProxyError)throw e;throw new TeacherProxyError(502,"upstream_unavailable","teacher service unavailable")}}
