package uploadintake

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"os"
	"path/filepath"
)

const MaxPDFBytes int64 = 25 * 1024 * 1024

// LocalQuarantineStore is development-only object storage. Its root must be outside the repo
// and is mounted from a private host directory in local environments.
type LocalQuarantineStore struct{ root string }

func NewLocalQuarantineStore(root string) (*LocalQuarantineStore, error) {
	if root == "" || !filepath.IsAbs(root) {
		return nil, errors.New("private upload root is not configured")
	}
	if err := os.MkdirAll(root, 0700); err != nil {
		return nil, err
	}
	return &LocalQuarantineStore{root: root}, nil
}
func (s *LocalQuarantineStore) Save(r io.Reader) (ref, hash string, size int64, err error) {
	var raw [16]byte
	if _, err = rand.Read(raw[:]); err != nil {
		return
	}
	ref = hex.EncodeToString(raw[:])
	path := filepath.Join(s.root, ref+".pdf")
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return
	}
	defer func() {
		_ = f.Close()
		if err != nil {
			_ = os.Remove(path)
		}
	}()
	h := sha256.New()
	limited := io.LimitReader(r, MaxPDFBytes+1)
	size, err = io.Copy(io.MultiWriter(f, h), limited)
	if err != nil {
		return
	}
	if size == 0 || size > MaxPDFBytes {
		err = errors.New("upload exceeds size limit")
		return
	}
	hash = hex.EncodeToString(h.Sum(nil))
	return
}

// Delete removes only an opaque reference generated by Save. It is used to clean an orphan when
// metadata persistence fails; retention workflow never calls it directly.
func (s *LocalQuarantineStore) Delete(ref string) error {
	if len(ref) != 32 {
		return errors.New("invalid object reference")
	}
	return os.Remove(filepath.Join(s.root, ref+".pdf"))
}
